[package]
name = "poi-radio"
version = "0.0.10"
edition = "2021"
authors = ["GraphOps (axiomatic-aardvark, hopeyen)"]
description = "POI Radio monitors subgraph data integrity in real time using Graphcast SDK"
license = "Apache-2.0"
repository = "https://github.com/graphops/poi-radio"
keywords = ["graphprotocol", "data-integrity", "Indexer", "waku", "p2p"]
categories = ["network-programming", "web-programming::http-client"]
default-run = "poi-radio"

[dependencies]
graphcast-sdk = { package = "graphcast-sdk", git = "https://github.com/graphops/graphcast-sdk", branch = "mocks" }
prost = "0.11"
once_cell = "1.15"
chrono = "0.4"
serde = "1.0.147"
serde_json = "1.0.87"
tokio = { version = "1.1.1", features = ["full"] }
anyhow = "1.0.69"
graphql_client = "0.9.0"
serde_derive = "1.0.114"
reqwest = { version = "0.11.0", features = ["json"] }
ethers = "2.0.0"
regex = "1.7.1"
ethers-contract = "2.0.0"
ethers-core = "2.0.0"
ethers-derive-eip712 = "2.0.0"
partial_application = "0.2.1"
num-bigint = "0.4.3"
num-traits = "0.2.15"
wiremock = "0.5.16"
dotenv = "0.15"
rand = "0.8.5"
secp256k1 = "0.25.0"
hex = "0.4.3"
tracing = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4.1.6", features = ["derive"] }
sha3 = "0.10.6"

[[bin]]
name = "integration-tests"
path = "integration-tests/src/main.rs"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
# Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"]
