version: "3"
services:
  basic-instance:
    build:
      context: .
      dockerfile: e2e-tests.Dockerfile
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY}
      GRAPH_NODE_STATUS_ENDPOINT: ${GRAPH_NODE_STATUS_ENDPOINT}
      REGISTRY_SUBGRAPH: ${REGISTRY_SUBGRAPH}
      NETWORK_SUBGRAPH: ${NETWORK_SUBGRAPH}
      GRAPHCAST_NETWORK: ${GRAPHCAST_NETWORK}
      RUST_LOG: ${RUST_LOG}
      INSTANCE: "basic"
  divergent-instance:
    build:
      context: .
      dockerfile: e2e-tests.Dockerfile
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY}
      GRAPH_NODE_STATUS_ENDPOINT: ${GRAPH_NODE_STATUS_ENDPOINT}
      REGISTRY_SUBGRAPH: ${REGISTRY_SUBGRAPH}
      NETWORK_SUBGRAPH: ${NETWORK_SUBGRAPH}
      GRAPHCAST_NETWORK: ${GRAPHCAST_NETWORK}
      RUST_LOG: ${RUST_LOG}
      INSTANCE: "divergent"
  invalid-payload-instance:
    build:
      context: .
      dockerfile: e2e-tests.Dockerfile
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY}
      GRAPH_NODE_STATUS_ENDPOINT: ${GRAPH_NODE_STATUS_ENDPOINT}
      REGISTRY_SUBGRAPH: ${REGISTRY_SUBGRAPH}
      NETWORK_SUBGRAPH: ${NETWORK_SUBGRAPH}
      GRAPHCAST_NETWORK: ${GRAPHCAST_NETWORK}
      RUST_LOG: ${RUST_LOG}
      INSTANCE: "invalid_payload"
  invalid-nonce-instance:
    build:
      context: .
      dockerfile: e2e-tests.Dockerfile
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY}
      GRAPH_NODE_STATUS_ENDPOINT: ${GRAPH_NODE_STATUS_ENDPOINT}
      REGISTRY_SUBGRAPH: ${REGISTRY_SUBGRAPH}
      NETWORK_SUBGRAPH: ${NETWORK_SUBGRAPH}
      GRAPHCAST_NETWORK: ${GRAPHCAST_NETWORK}
      RUST_LOG: ${RUST_LOG}
      INSTANCE: "invalid_nonce"
  invalid-block-hash-instance:
    build:
      context: .
      dockerfile: e2e-tests.Dockerfile
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY}
      GRAPH_NODE_STATUS_ENDPOINT: ${GRAPH_NODE_STATUS_ENDPOINT}
      REGISTRY_SUBGRAPH: ${REGISTRY_SUBGRAPH}
      NETWORK_SUBGRAPH: ${NETWORK_SUBGRAPH}
      GRAPHCAST_NETWORK: ${GRAPHCAST_NETWORK}
      RUST_LOG: ${RUST_LOG}
      INSTANCE: "invalid_hash"
