name: Build and upload Docker image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  BASE_NAME: graphops/poi-radio

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.BASE_NAME }}
